-- 코드를 입력하세요
SELECT A.FLAVOR FROM FIRST_HALF A
LEFT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL FROM JULY GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + IFNULL(B.JULY_TOTAL,0)) DESC
LIMIT 3;